spring:
  profiles:
    active: local # 로컬에서 돌린다는 의미 (보통 local, 개발은 (dev, develop), 운영은 (real) 이런 식으로 함)
  datasource:
#    url: jdbc:h2:tcp://localhost/~/querydsl
    url: jdbc:h2:file:~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #    show_sql: true
        format_sql: true
        use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace