spring:
  datasource:
    url: jdbc:h2:file:~/japshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #기본으로 create-drop 으로 돌아감. 애플리케이션 종료 후 드랍해줌
    properties:
      hibernate:
# 운영에서는 sout 대신 로그로 찍는다.
#       show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace