DROP TABLE IF EXISTS NOTICE;

create table NOTICE
(
    ID BIGINT auto_increment primary key,
    TITLE     VARCHAR(255),
    CONTENTS  VARCHAR(255),

    HITS            INTEGER,
    LIKES           INTEGER,
    REG_DATE        TIMESTAMP,
    UPDATE_DATE     TIMESTAMP,
    DELETED_DATE    TIMESTAMP,
    DELETED         BOOLEAN
);

create table user
(
    id bigint generated by default as identity,
    email varchar(255),
    password varchar(255),
    phone varchar(255),
    reg_date timestamp,
    user_name varchar(255),
    update_date timestamp,
    primary key (id)
);